### ISSUE TITLE
Mod crashes on Tick

### ISSUE THREAD

**Issue by dreckz** [Mrbysco/Spoiled#1]
## Client Info
* Minecraft Version: 1.15.2

* Forge Version: 31.1.30
* Mod Version: 1.1
* Java Version: 8

## Issue Description
Upon the ticking in the world, the mod a crashes due to a misfire

## Reproduce Steps
Explore around the world and wait for the crash to occur

## Additional Information

Crash Report:
https://paste.gg/p/anonymous/e7b351050e40443f8a0a5f66e0aa0c88

**Comment by Mrbysco** [comment]
Could you check if the crash still occurs with 1.1.0.1 (Available on Curseforge)

**Comment by dreckz** [comment]
[crash-2020-04-01_14.36.06-server.txt](https://github.com/Mrbysco/Spoiled/files/4417295/crash-2020-04-01_14.36.06-server.txt)

Crash still occurs

**Comment by Mrbysco** [comment]
Gonna release another version in a few minutes.

**Comment by Mrbysco** [comment]
New version is out that should fix the problem

**Comment by slard3** [comment]
keeps crashing

MC version: 1.15.2
Forge version: 31.1.30
Spoiled version: 1.15-1.1.0.2
[Crash report](https://paste.gg/p/anonymous/6f8dca740cca4559bdaf71e142a2491f)

**Comment by Mrbysco** [comment]
Could you test the build I put in the releases (1.1.0.3)
https://github.com/Mrbysco/Spoiled/releases/tag/1.1.0.3
If it fixes it I'll upload it to Curse

**Comment by slard3** [comment]
Spoiled version: 1.1.0.3
[Crash report](https://paste.gg/p/anonymous/90664163e10f4dffbb6489313fce9910)

**Comment by Mrbysco** [comment]
Could you test a new build? https://github.com/Mrbysco/Spoiled/releases/tag/1.1.0.4

**Comment by slard3** [comment]
It's been a while with the mod loaded and it hasn't crashed, I guess you've fixed! :)
