### ISSUE TITLE
whats is the format of adding new container?

### ISSUE THREAD

**Issue by VictorSPM** [Mrbysco/Spoiled#13]
in the common config, i saw that [Syntax: tileentity:spoil_rate] is the format, and it gave an example of "minecraft:shulker_box,0"
however i kept getting errors when adding an item, whats the syntax?

i want to add MrCRAYFISH's furniture fridge, i tried ["MrCrayfish's_Furniture:fridge_(light),0.1"] and ["cfm:fridge_(light),0.1"] but both failed. so how do you add new items or items from other mods?
[crash-2021-07-20_18.00.43-client.txt](https://github.com/Mrbysco/Spoiled/files/6847326/crash-2021-07-20_18.00.43-client.txt)

**Comment by VictorSPM** [comment]
what are u suppose to do if it have a () in its name?

**Comment by Mrbysco** [comment]
The `containerModifier` uses the tileentity resource location. I'm adding a command `/spoiled tileentity list` to list the tile entities in the log which will make it easier.

Try `["cfm:fridge,0.1"]`

**Comment by VictorSPM** [comment]
Thx for the reply, i found my solution by checking the mod's asset and found that it has a different name. Hope to get that command soon, before that if any others have a problem with the tileentity i found a mod that will tell you the tileentity and id. its called tellme hope this helps you
