### ISSUE TITLE
modded container's spoil rate wont change

### ISSUE THREAD

**Issue by VictorSPM** [Mrbysco/Spoiled#14]
- [x] I am running a modpack
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I am using the latest version of the mod

## Client Info
* Minecraft Version:1.16.5
* Forge Version: 1.16.5-36.1.51
* Mod Version: 1.4.0
* Java Version: build 1.8.0_291-b10

## Issue Description
after being able to add the mod containers to the config, i found that the spoiled time in a configured container and a normal oak chest is the same even though i set the spoiled time as 0.1 which should be 200mins meaning 2 mins for 1% of spoil rate but the rate is same as in the oak chest.

## Reproduce Steps
i have cfm downloaded and edited the spoiled-common.toml 
containerModifier = ["minecraft:shulker_box,0", "cfm:fridge_light,0.1", "cfm:fridge_dark,0.1", "sophisticatedbackpacks:backpack,0.35", "sophisticatedbackpacks:iron_backpack,0.3", "sophisticatedbackpacks:gold_backpack,0.25", "sophisticatedbackpacks:diamond_backpack,0.2", "sophisticatedbackpacks:netherite_backpack,0.15", "immersiveengineering:toolbox,0.5", "industrialforegoing:infinity_backpack,0"]

**Comment by Mrbysco** [comment]
Could you provide your config and a list of mods you're using?

**Comment by VictorSPM** [comment]
> Could you provide your config and a list of mods you're using?
Spice of Life
Better Animals Plus
serene seasons
Subterranean Wilderness
Better Caves
Better Mineshafts
Improved Mobs
When Dungeons Arise
Repurposed Structures
Artifacts
Oh the Biomes You'll Go
Sophisticated Backpacks
Corpse
BetterEnd
SecurityCraft
Carry On
Platforms
Ironchest
The Twilight Forest
Alex's Mobs
Macaw's Fences & Walls
Macaw's door
Macaw's window
Macaw's bridge
Macaw's light
Macaw's furniture
Macaw's roof
Macaw's trapdoors
Enhanced Celestials
Cosmetic Armor
comforts
Thut’s Elevator
Realistic torch 
Ice and fire
SURVIVE
Dungeon crawl
Mrcrayfish furniture 
Pams food core
Pams tree 
Pams crops 
Pams food extended
Mowzie's Mobs -
DEUF
Chocolate fix
Lycanites Mobs
AttributeFix
Chisel
Tool belt
Snow real magic
MmmMmmm
Dynamaxe
Upstream
Extra boats
AstikorCarts
ArmorPlus
Useful Railroads
Translocators 1.8.+
Waystones
JEI
Spoiled
Clump
Tinker construct
Immersive engineering 
Mekanism
AE2
Industrial foregoing 
Thermal expansion 
The Abyss: Chapter II
Storage drawer

Mouse tweak
Neat
Hwyla
Sound filter
Dynamic surrounding 
overloaded toughness bar
appleskin

#spoiled-common.toml

#General settings
[General]
	#Defines the default amount of spoilTime (in second) that is used to initialize Spoiling when 'initializeSpoiling' is enabled
	#Range: > 1
	defaultSpoilTime = 120
	#Determines the spoilrate in specific containers [Syntax: tileentity:spoil_rate]
	#Examples: "minecraft:shulker_box,0" would make shulker boxes not spoil food
	#"cookingforblockheads:fridge,0.2" would make a cooking for blockheads fridge spoil at 20% of the usual spoilrate
	containerModifier = ["minecraft:shulker_box,0", "cfm:fridge_light,0.1", "cfm:fridge_dark,0.1", "sophisticatedbackpacks:backpack,0.35", "sophisticatedbackpacks:iron_backpack,0.3", "sophisticatedbackpacks:gold_backpack,0.25", "sophisticatedbackpacks:diamond_backpack,0.2", "sophisticatedbackpacks:netherite_backpack,0.15", "immersiveengineering:toolbox,0.5", "industrialforegoing:infinity_backpack,0"]
	#When enabled Spoiled initializes spoiling for all vanilla food
	initializeSpoiling = true
	#Defines the item the foods vanilla foods will turn into when spoiled (if empty it will clear the spoiling item) [default: 'minecraft:rotten_flesh']
	defaultSpoilItem = "minecraft:rotten_flesh"
	#Defines the default amount of seconds in between which the spoiling updates, if this is changed you should update the 'defaultSpoilTime' to accommodate for the extra time [default: 10]
	#Range: > 1
	spoilRate = 10

**Comment by Mrbysco** [comment]
1.4.2 has been uploaded to CurseForge which fixes this issue

**Comment by VictorSPM** [comment]
Do i need to add sth or do something special? as the update did not fix the issue, or did it work for you? as I downloaded the 1.4.2 into a test pack which only have the mod and cfm, then I configured the config as it is. but the spoil rate seems just the same. i have deleted the config files of the previous version so that it will not affect the result.



#General settings
[General]
	#Defines the default amount of spoilTime (in second) that is used to initialize Spoiling when 'initializeSpoiling' is enabled
	#Range: > 1
	defaultSpoilTime = 120
	#Determines the spoilrate in specific containers [Syntax: tileentity:spoil_rate]
	#Examples: "minecraft:shulker_box,0" would make shulker boxes not spoil food
	#"cookingforblockheads:fridge,0.2" would make a cooking for blockheads fridge spoil at 20% of the usual spoilrate
	containerModifier = ["minecraft:shulker_box,0", "cfm:fridge_light,0.1", "cfm:fridge_dark,0.1"]
	#When enabled Spoiled initializes spoiling for all vanilla food
	initializeSpoiling = true
	#Defines the item the foods vanilla foods will turn into when spoiled (if empty it will clear the spoiling item) [default: 'minecraft:rotten_flesh']
	defaultSpoilItem = "minecraft:rotten_flesh"
	#Defines the default amount of seconds in between which the spoiling updates, if this is changed you should update the 'defaultSpoilTime' to accommodate for the extra time [default: 10]
	#Range: > 1
	spoilRate = 10

**Comment by VictorSPM** [comment]
i dont know much about making mods, but i was looking at the github file and there is a new file called gradle.properties but i cant find that in the .jar file, did u not put it in or i am just a noob

**Comment by Mrbysco** [comment]
You're using the block name's instead of the tile entity names.

To find the Tile Entity names you can use `/spoiled tileentity list` and check the `latest.log` in the `logs` folder
