### ISSUE TITLE
Items not stacking

### ISSUE THREAD

**Issue by etroozo** [Mrbysco/Spoiled#15]
## Client Info
* Minecraft Version: 1.16.5

* Forge Version: 36.1.32 & 36.2.0
* Mod Version: 1.4.2
* Java Version:  Version 8 update 291 (build 1.8.0_291-b10)

When I have this mod loaded, I experience a bug that causes identical items not to stack together. For instance, if I have 30 dirt in my inventory, and I gathered some more, it would start it's own stack. If I try to combine the two stacks, they simply swap places (like they would if they were stacks of different blocks). This happens with every kind of stackable item I've tested so far, vanilla and modded.

## Reproduce Steps
Since I seem to be the only person having this problem, I'd assume it's a conflict with one of the many other mods I have loaded, so running those particular mods would probably number one. [Here's my modlist.](https://pastebin.com/nH3yC9rB)
I have trouble reproducing this in survival mode (it happens but only sometimes, I'm not sure what causes it) I can 100% reproduce it in creative by doing the following:
-give yourself some blocks (not a full stack)
-place some of those blocks in the world
-enter survival mode
-harvest the blocks in survival mode

They should go into your inventory but form a separate stack. 

## Additional Information

[Video](https://imgur.com/a/1lxYvhY)

**Comment by Mrbysco** [comment]
Could you try to reproduce it with 1.4.2.1 that I just released on Curse?

**Comment by etroozo** [comment]
> Could you try to reproduce it with 1.4.2.1 that I just released on Curse?

Hey, that seems to have fixed it. Thanks a ton for the speedy support!
