### ISSUE TITLE
Spoiled Description showing "s" instead of stale/fresh/something else

### ISSUE THREAD

**Issue by TqLxQuanZ** [Mrbysco/Spoiled#16]
## Client Info
* Minecraft Version: 1.16.5

* Forge Version: 36.2.0
* Mod Version: Spoiled-1.16.5-1.4.2.1
* Java Version: build 1.8.0_301-b09

## Issue Description

Spoiled description for the second stage shows only "s". In between Fresh and Stale.

## Reproduce Steps

1. Awaits the food to spoil from Fresh.

**Comment by Mrbysco** [comment]
That spoiling stage used to be empty, I have no clue how that "s" sneaked in there
