### ISSUE TITLE
Crash on worldgen

### ISSUE THREAD

**Issue by LokyLive** [Mrbysco/Spoiled#2]
## Client Info
* Minecraft Version: 1.15.2

* Forge Version:  31.1.45
* Mod Version: 1.15-1.1.1
* Java Version:  1.8.0_51

## Issue Description
Just crash on generating new chunk

## Additional Information

crash report : https://hastebin.com/efodegefag.pl

**Comment by Mrbysco** [comment]
I guess this is a continuation of https://github.com/Mrbysco/Spoiled/issues/1 which I thought got fixed.

**Comment by Mrbysco** [comment]
This crash is hard to reproduce in development. It seems to crash if there's many mods installed which is weird.

**Comment by LokyLive** [comment]
I will try to investigate more about it.

**Comment by LokyLive** [comment]
Ok so same crash with only spoiled as mod 

crash log: https://hastebin.com/orewozohoc.php

**Comment by Mrbysco** [comment]
What were you doing while it happened?

**Comment by Mrbysco** [comment]
I've reproduced it. And made a tiny change which might fix it.

If you could test https://github.com/Mrbysco/Spoiled/releases/tag/1.1.2 and see if you run into the same issues.

**Comment by LokyLive** [comment]
it seems to works, just one question when i've got food in hand , my hand is following food's tickrate update ? xD

**Comment by Mrbysco** [comment]
I don't know if there's a way to not display the item update animation when holding it.

If you could try with other mods that'd be great.

**Comment by LokyLive** [comment]
tested with many mods and it seems to be fixed, good job !

**Comment by Mrbysco** [comment]
Version is uploaded to CurseForge
