### ISSUE TITLE
[Bug]: Removing spoilage not working

### ISSUE THREAD

**Issue by pwigary** [Mrbysco/Spoiled#22]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

36.2.20

### Mod version

1.16.5 - 1.4.3

### Java version

Java 11

### Issue Description

Hi mod creator, I am unable to remove an item from spoilage using the syntax provided in the wiki. I have tried the following:

spoiling.removeRecipeByInput(item:minecraft:spider_eye input);
spoiling.removeRecipeByInput(item:minecraft:spider_eye);
spoiling.removeByName(minecraft:spider_eye);
...

It always return "Parser Exception" when the scripts are reloaded.

**Comment by Mrbysco** [comment]
Have you checked the wiki page and it's example?
https://github.com/Mrbysco/Spoiled/wiki/Post-1.4

**Comment by pwigary** [comment]
I have checked it, and there isn't an example for the removal, could you provide one here?

**Comment by Mrbysco** [comment]
I've updated the wiki and introduced a new example

**Comment by pwigary** [comment]
It still doesn't work :/ is the example you provide for 1.16? Cause I'm reporting this as 1.16.

**Comment by pwigary** [comment]
I have wrote one again for 1.16, but this time it says not such member. Maybe you should try it.

**Comment by Mrbysco** [comment]
In 1.16 it's **removeRecipeByInput**

**Comment by pwigary** [comment]
Okay, but the wiki stated something else, just letting you know.

**Comment by Mrbysco** [comment]
The wiki was going off the names in 1.18, but apparently it was different in 1.16
