### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ronanfalcon** [Mrbysco/Spoiled#25]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

36.2.21

### Mod version

1.5.0

### Java version

1.8.0_312 Eclipse OpenJ9 VM

### Issue Description

Containers from MrCrayfish's Furniture mod are not working in the container modifier system.
I tried it these past days, and none of them worked - tried the fridge and the coolers, of course, but even others are not working.

**Comment by Mrbysco** [comment]
Works fine for me
