### ISSUE TITLE
[Suggestion]: Allow Items to Be Given Unique Settings for What They Rot Into

### ISSUE THREAD

**Issue by Darkosto** [Mrbysco/Spoiled#28]
### General Info

- [X] I would like to propose new content
- [X] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Hey it's ya boi, Darktoasto,

Can you look into allowing a config setting so I can have specified food items rot into another item rather than 1 config option? Is it better to set it as a custom spoiling recipe and tweakable in a datapack?

Sincerely, 
Ya boi, darksosto

**Comment by Mrbysco** [comment]
Is already possible when using the recipe system that's built in :)
