### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Aethamus** [Mrbysco/Spoiled#29]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.52

### Mod version

1.18.2-1.5.6

### Java version

Java 8 Update 341

### Issue Description

Changing the default spoil item doesn't work at all and having it empty instantly removes the item no matter what the spoil time and rate are set to

**Comment by Mrbysco** [comment]
Could you provide the config file where you tried changing the default spoil item?

**Comment by Aethamus** [comment]
@Mrbysco 
Sorry
The issue was with the Configured mod changing the config in-game. I manually changed it in the folder and it works now.
