### ISSUE TITLE
A few bugs and suggested fix

### ISSUE THREAD

**Issue by bloche1871** [Mrbysco/Spoiled#3]
1) Food doesn't spoil in vanilla barrels
2) Food doesn't spoil in most mod containers I tested
3) Food doesn't spoil in containers that are in item form (shulker box - like containers)
4) Food seems to animate weirdly when held in hand, as if player is switching between different items

My impression is that this is all due to the way the spoiling works by ticking through containers. Maybe one way to fix that (and to increase performance) would to change to a system where items store the value of getTotalWorldTime() when they were created, and are only checked for spoilage when needed (when moving them or opening a container for example), based on the difference between that stored value and the current getTotalWorldTime()

**Comment by Mrbysco** [comment]
1, 2 and 4 has been fixed in recent version (as far as I know)
3 remains a thing I gotta look into.
