### ISSUE TITLE
[Bug]: Spoiling food unable merge

### ISSUE THREAD

**Issue by wumengzhixing** [Mrbysco/Spoiled#30]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.84

### Mod version

Spoiled-1.18.2-1.5.7

### Java version

jkd-17.0.4.1

### Issue Description

I have enabled merge in spoiled, but it is not possible to merge spoiling food in fact
	#When enabled enables a special recipe to merge spoiling food together [default: false]
	mergeSpoilingFood = true
I hope you can help me solve this problem.

### Additional Information

![1](https://user-images.githubusercontent.com/88496786/202644334-7326aef7-3def-4684-8fa3-b60bce4f479c.png)

**Comment by Mrbysco** [comment]
Merging only works in a crafting grid

**Comment by wumengzhixing** [comment]
> Merging only works in a crafting grid

Can you do this feature?
Too much spoiled food won't fit in the backpack
Let the rotten food can be stacked, stacked to reduce the degree of rot
