### ISSUE TITLE
[Bug]: character length limit

### ISSUE THREAD

**Issue by SeanChengN** [Mrbysco/Spoiled#35]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.1.28

### Minecraft version

1.20.1

### Mod version

2.0.0

### Java version

Java 17.0.7

### Issue Description

The container id setting seems to have a length limit.
![java_j9CD89h6JC](https://github.com/Mrbysco/Spoiled/assets/20624068/e30c49f0-764c-4c37-87b7-3cc8f71552f4)

**Comment by Mrbysco** [comment]
It doesn't have a limit, I feel like you're being limited to whatever adds that config screen

**Comment by SeanChengN** [comment]
> It doesn't have a limit, I feel like you're being limited to whatever adds that config screen

Well, looks like a known issue with ForgeConfigScreens @Fuzss 
https://github.com/Fuzss/forgeconfigscreens/issues/4

**Comment by Mrbysco** [comment]
I've never used that mod before, I usually use Configured whenever I need an in-game config
