### ISSUE TITLE
[Bug]: The mod doesn't work

### ISSUE THREAD

**Issue by jaimarl** [Mrbysco/Spoiled#38]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Forge 43.2.21

### Minecraft version

1.19.2

### Mod version

1.6.3

### Java version

17.0.8+7

### Issue Description

I installed the mod in my modpack and found that it does not display the degree of food spoilage. Then I installed the mod on a clean version 1.19.2 without any other mods at all and encountered the same problem. I waited 30 minutes and the food did not spoil.

**Comment by Mrbysco** [comment]
Are you in creative? as it doesn't spoil your inventory when you're in creative

**Comment by jaimarl** [comment]
Ah, yeah I haven't even tried testing in survival. Everything works, thanks!
