### ISSUE TITLE
Spoilage not working

### ISSUE THREAD

**Issue by The-Brandolorian** [Mrbysco/Spoiled#4]
## Client Info
* Minecraft Version:1.16.5

* Forge Version: 36.0.37
* Mod Version: 1.3
* Java Version: build 1.8.0_281-b09

## Issue Description
Spoilage does not work, I've enabled percentages but no matter how long I wait food never begins to spoil.

## Reproduce Steps
-

**Comment by Mrbysco** [comment]
What food isn't spoiling? As by default only vanilla foods spoil.
I'm unable to reproduce this issue. In an environment with just Spoiled apples spoilage progresses every 10 seconds

**Comment by The-Brandolorian** [comment]
Not even the vanilla food spoils, I'm playing in my own modpack - https://www.curseforge.com/minecraft/modpacks/creations-adventures
I have multiple mods that alter the food system so I assume one of them is conflicting?

**Comment by The-Brandolorian** [comment]
I've done some testing, slowly adding mods in. turns out this does not occur in single player, only on my personal server. strange.

**Comment by UkeIdiot** [comment]
Have you maybe checked to see if it's on the server? If so, check if it's up to date.

**Comment by The-Brandolorian** [comment]
yeah it's on there, version - 'Spoiled-1.16.5-1.3'
I might try and test it on a freshly installed server when I get a chance and see if it persists or if its a mod conflict.

**Comment by Mrbysco** [comment]
https://www.curseforge.com/minecraft/mc-mods/spoiled/files/3208358
