### ISSUE TITLE
[Question]:  How can I change the time of spoiling?

### ISSUE THREAD

**Issue by iulikjulik** [Mrbysco/Spoiled#44]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

How can I change the time of spoiling? sry i am dumb

**Comment by Mrbysco** [comment]
https://github.com/Mrbysco/Spoiled/wiki/Spoil-Rate-and-Spoil-Time

**Comment by iulikjulik** [comment]
> https://github.com/Mrbysco/Spoiled/wiki/Spoil-Rate-and-Spoil-Time

i am too dumb, is it in the config file?(where is it?) or in game?

**Comment by iulikjulik** [comment]
i solved, sorry for interuption
