### ISSUE TITLE
[Bug]: food spoils in containers added in the container modifier with a value of 0

### ISSUE THREAD

**Issue by meltremb** [Mrbysco/Spoiled#46]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

fabric 0.15.11

### Minecraft version

1,20,1

### Mod version

2.0.4

### Java version

java 8 update 381

### Issue Description

i am using this mod with paladin's furniture mod (and a bunch of others) but pfm adds fridges, so i added the fridges to the container modifier alongside the shulker box with the same syntax, i am running on a server i host myself, both the client and server config are the exact same (copy pasted). however i also blacklisted a bunch of items from croptopia to prevent them from spoiling, and that seems to work fine, so i'm not sure why the food keeps spoiling in the fridges.
![foodinfridge](https://github.com/Mrbysco/Spoiled/assets/104160956/66e89969-2725-4c1d-94dd-2c1f1e71fdfe)
![Config](https://github.com/Mrbysco/Spoiled/assets/104160956/44a97b2b-f22a-4682-af50-9696aeaa56e8)

**Comment by Mrbysco** [comment]
Are you sure you configured it correctly? The config takes in the block entity if not the block

**Comment by meltremb** [comment]
Ooooh I didn't know that. I've looked it up a little bit but I'm not sure how to know the name of the block entity. How can i do that?

**Comment by Mrbysco** [comment]
There's a command `/spoiled list blockentity` or something like that. That will list out all Block Entity ids in the log

**Comment by meltremb** [comment]
Thanks! I found it and put that in the config instead and now it works!
