### ISSUE TITLE
[Bug]: No footsteps

### ISSUE THREAD

**Issue by NuttySamGreen** [Mrbysco/Spoiled#53]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Loader version

Fabric 0.15.11

### Minecraft version

1.20.1

### Mod version

2.0.4

### Java version

Java 17

### Issue Description

walking around in a world doesn't make footsteps noise
I would expect to hear footsteps noise
I wouldn't think it would be this mod but I reset the modpack to before I installed it and the problem was gone
it's a pretty cool mod and is well made, I just don't know why it's breaking my sound

### Additional Information

The modpack I'm using
https://modrinth.com/modpack/lagaree/version/BDmlYtwa
it is mine. the problem exists in 1.3.0
I am using presence footsteps

**Comment by Mrbysco** [comment]
This mod does not touch sounds

**Comment by NuttySamGreen** [comment]
My bad, I somehow turned off the sound resourcepack when I installed the mod
