### ISSUE TITLE
[Suggestion]: Compatibility with realistic mods

### ISSUE THREAD

**Issue by TheRTGGaming** [Mrbysco/Spoiled#56]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Can you make the mod compatible with 2 mods that make sense.

MrCrayFishes: Furniture Mod: Refurbished [fridge]
https://www.curseforge.com/minecraft/mc-mods/refurbished-furniture

and

Real Time Mod
https://www.curseforge.com/minecraft/mc-mods/real-time-mod

**Comment by Mrbysco** [comment]
You can already configure compatibility with the furniture mod in the config.

I have no plans of having the compat be built in
