### ISSUE TITLE
[Bug]: flint and steel dupe

### ISSUE THREAD

**Issue by Axzyo** [Mrbysco/Spoiled#59]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

quilt 0.26.4

### Minecraft version

1.20.1

### Mod version

2.1.2

### Java version

I am not quite shure but I recently updated java

### Issue Description

There is an option that allows players to merge foods at different levels of spoilage. when I turn this on the food merging works perfect but I tried merging 2 flint and steel in my inventory and it started duping the flint and steel. From what I saw, the two flint and steel items in the crafting grid lost durability each time I preformed the craft/dupe.
Edit: I have not tested this with swords, armour or any other "durability having items" but I assume it does the same thing.

hope this helps, thanks for the cool mod :)

**Comment by Mrbysco** [comment]
The food merging only works on literal foods, it does not touch tool merging.
I'm unable to reproduce the bug on 1.20.1 Fabric. (I do not officially support Quilt)
