### ISSUE TITLE
defaultSpoilItem in serverconfig doesn't work

### ISSUE THREAD

**Issue by Minothilos** [Mrbysco/Spoiled#6]
## Client Info
* Minecraft Version: 1.16.5

* Forge Version: 36.0.42
* Mod Version: 1.3.3
* Java Version: 1.8.0_281-b09

## Issue Description
The "defaultSpoilItem" config option in serverconfig doesn't work

## Reproduce Steps
Start a new world, change defaultSpoilItem in the serverconfig (tested with "crockpot:wet_goop" and "minecraft:dirt") restart game, put vanilla food item in inventory (tested with vanilla carrots and bread), wait for it to spoil. It will always spoil into rotten flesh, instead of specified item.

## Additional Information
Server config for spoil:
[https://pastebin.com/7FsPvJ9G](url)

**Comment by Mrbysco** [comment]
Have a log? As it should throw an error if it were to revert to rotten flesh

**Comment by Mrbysco** [comment]
I have changed the config to be a common config (aka one that goes in the regular config folder) as apparently server-configs don't load early enough (for my use-case)

**Comment by Mrbysco** [comment]
If you could test if https://github.com/Mrbysco/Spoiled/releases/tag/1.3.4 fixes your issue

**Comment by Minothilos** [comment]
The new config works as intended, thanks!
