### ISSUE TITLE
Food still doesn't spoil in a lot of modded containers

### ISSUE THREAD

**Issue by Minothilos** [Mrbysco/Spoiled#7]
## Client Info
* Minecraft Version: 1.16.5

* Forge Version: 36.0.42
* Mod Version: 1.3.3
* Java Version: 1.8.0_281-b09

## Issue Description
Spoiling doesn't work in a lot of (non-chest) containers, including Farmer's Delight Pantries, Builders Crafts & Additions counters, cabinets and bedside tables, Essentails Slotted Chest and Vanilla Barrels. All chest I've tested work, including chests from Quark, Iron Chests, and Terra Incognita. Adjustable Crates from Create also work (which is the only non-chest container with a GUI that works).

## Reproduce Steps
Put food in a non-chestlike container and watch it not spoil

## Additional Information

Modlist:
[https://pastebin.com/VK25Qn2n](url)

**Comment by Mrbysco** [comment]
If you could test if https://github.com/Mrbysco/Spoiled/releases/tag/1.3.4 fixes your issue

**Comment by Minothilos** [comment]
Spoiling now works in all containers I tested, thanks a lot!
