### ISSUE TITLE
A little more inventory friendly idea

### ISSUE THREAD

**Issue by HopsandBarley** [Mrbysco/Spoiled#8]
## SUGGESTIONS
- [ ] I would like to propose new content.
- [x] I would like to propose changes.
- [ ] I would like to propose another thing.

## SUGGESTION INFORMATION

Started playing around with your mod today.  Really has a lot of potential.  One idea I had, though, was to find a way to make food a little more stackable.  I killed 3 sheep in a span of 30 seconds, and ended up with 3 stacks of mutton 1-2 each.  they were not stackable, even though 2 of them had the same % spoiled.  

Is it possible to 'adjust' the spoil rate, where it would only tick say, every 5%?  and anything within the same  5% spoilage rate would then be stackable?  

Just a thought.  I really like what you have, outside of that.

**Comment by HopsandBarley** [comment]
`Started playing around with your mod today.  Really has a lot of potential.  One idea I had, though, was to find a way to make food a little more stackable.  I killed 3 sheep in a span of 30 seconds, and ended up with 3 stacks of mutton 1-2 each.  they were not stackable, even though 2 of them had the same % spoiled.  

Is it possible to 'adjust' the spoil rate, where it would only tick say, every 5%?  and anything within the same  5% spoilage rate would then be stackable?  

Just a thought.  I really like what you have, outside of that.

**Comment by Mrbysco** [comment]
Fixed the issue template and the issue

**Comment by Mrbysco** [comment]
The spoil rate is configurable :) By default I changed the value to make it spoil a bit every 10 seconds. Could be adjusted to 30 in the config
