### ISSUE TITLE
[bug] containerModifier in common config doesn't work

### ISSUE THREAD

**Issue by Minothilos** [Mrbysco/Spoiled#9]
## Client Info
* Minecraft Version: 1.16.5

* Forge Version: 36.0.42
* Mod Version: 1.3.4
* Java Version: 1.8.0_281-b09

## Issue Description
The custom spoil rates set by the containerModifier in the common config doesn't seem to work. After setting some containers to not spoil/spoil slower nothing happened after reload/restart. I've tested with Farmers Delight pantries, Iron Chests and Vanilla Barrels and adding those to the list following the example formating didn't work. Removing Shulker boxes from the list made food spoil in shulker boxes (although I haven't tested if spoiling worked/didn't work while it was still on the list).

On a slightly different note, food doesn't spoil in shulker boxes while the box is in an inventory, food also doesn't spoil in inventories like backpacks (I've only tested with backpacks from MrCrayfish's Backpacked and Backpacker but I would assume this goes for basically all backpack mods) I realise this could be hard to fix but does unfortunetly make cheesing the hell out of the mod very easy as soon as you start exploring the end or a lot sooner depending on the mod list.

(also food doesn't spoil in containers without a GUI, for example storage drawers, this doesn't really have a meaningful impact on gameplay. It's a very clunky way to store food since food of different spoilage doesn't go into the same drawer, just thought it was worth noting)

## Reproduce Steps
Add (for example) "minecraft:barrel,0" to the containerModifier list, launch the game, insert food, watch it still spoil.

## Additional Information
Config: 
[https://pastebin.com/PNP4HDHN](https://pastebin.com/PNP4HDHN)

Modlist:
[https://pastebin.com/V9ewmXwe](https://pastebin.com/V9ewmXwe)

Hope I've not cause too much of a headache with all these requests. I've been playtesting a WIP modpack these last couple of days and this mod is one of the corner pieces. I really appreciate all the work you've done, thanks!

**Comment by Wedge1453** [comment]
I experience the same problem, I tested with farmer's delight (and abnormal delights) pantries, crumbs barrels + the vanilla one, and shulkers.

and yes food doesn't spoil in player inventory or related inventories like backpacks, shulker boxes, lunchboxes etc...
this is my config file: 
[spoiled-common.txt](https://github.com/Mrbysco/Spoiled/files/6166974/spoiled-common.txt)

**Comment by Mrbysco** [comment]
Finally managed to narrow down the issue. I derped the implementation :) Fix incoming
